#!/usr/bin/env bash
# Install the morning refresh as a launchd job. Run it once:
#
#     bash tools/install_refresh_job.sh
#
# It writes the plist itself, using this checkout's real path, and
# loads it. Nothing to hand-edit.
#
# WHY THIS REPLACED A TEMPLATE YOU EDITED BY HAND
# The old way was: copy tools/com.boxscorewhisperer.refresh.plist into
# ~/Library/LaunchAgents, change /Users/CHANGE_ME/... to your path,
# launchctl load. That worked, and the job still never ran once in
# three days:
#
#     $ launchctl list | grep boxscore
#     -  126  com.boxscorewhisperer.refresh
#     $ cat /tmp/boxscore-refresh.err
#     /bin/bash: /Users/.../Documents/Boxscore-Whisperer/tools/
#               scheduled_refresh.sh: Operation not permitted
#
# The path was right. macOS was the problem: Documents, Desktop and
# Downloads are TCC-protected, and the /bin/bash that launchd spawns has
# no permission to read them. It could not open the script, so not one
# line of the refresh ever executed -- and launchd cannot raise a
# consent prompt at 08:30 with nobody at the machine, so it failed
# silently every morning and logged only to a file in /tmp that nobody
# had reason to look at.
#
# A stale cache is this app's quietest failure: nothing breaks, the
# projections just keep describing last week. So the check below is the
# point of this script. It refuses to install into a protected folder
# rather than letting you find out by noticing, three days later, that
# the numbers stopped moving.

set -uo pipefail

LABEL="com.boxscorewhisperer.refresh"
HOUR=8
MINUTE=30

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"

say() { printf '  %s\n' "$*"; }
die() { printf '\nSTOPPED: %s\n' "$*" >&2; exit 1; }

echo
say "repo:  $REPO_DIR"
say "plist: $PLIST"
echo

# ---- the check this script exists for --------------------------------
# Matched on the path rather than by trying a read, because the shell
# running this HAS your terminal's permissions -- it can read Documents
# perfectly well. The process that cannot is the one launchd spawns at
# 08:30, which is not this one. Testing here would pass and prove
# nothing.
case "$REPO_DIR/" in
    "$HOME/Documents/"*|"$HOME/Desktop/"*|"$HOME/Downloads/"*)
        protected="${REPO_DIR#$HOME/}"
        protected="${protected%%/*}"
        die "this checkout is inside ~/$protected, which macOS protects.

  A launchd job cannot read it: the job would be installed, report exit
  code 126, and never run a single line -- silently, every morning.

  Move the repo somewhere unprotected first, then run this again:

      mkdir -p ~/Projects
      mv \"$REPO_DIR\" ~/Projects/
      cd ~/Projects/$(basename "$REPO_DIR")
      bash tools/install_refresh_job.sh

  The home folder itself is not protected, so ~/Projects needs no
  permission grant at all. git history, remotes and data_cache.zip are
  unaffected by the move."
        ;;
esac
say "not in a macOS-protected folder -- launchd will be able to read it"

[ -f "$REPO_DIR/tools/scheduled_refresh.sh" ] || die "tools/scheduled_refresh.sh is missing"

# ---- which python, decided here and written into the job -------------
# launchd hands a job a bare environment: PATH is /usr/bin:/bin:
# /usr/sbin:/sbin and nothing else. So `python3` there resolves to
# macOS's own /usr/bin/python3, which has no third-party packages, and
# the first real run of this job died on:
#
#     ModuleNotFoundError: No module named 'pandas'
#
# after the TCC fix had already got it as far as running. The python
# that matters is the one on YOUR PATH, which this installer can see
# because it runs in your shell -- so it is resolved here, checked
# here, and written into the plist rather than looked up at 08:30.
PYTHON_BIN="$(command -v python3 2>/dev/null || true)"
[ -n "$PYTHON_BIN" ] || die "no python3 on PATH -- cannot tell the job which python to use"
PYTHON_DIR="$(cd "$(dirname "$PYTHON_BIN")" && pwd -P)"
PYTHON_BIN="$PYTHON_DIR/$(basename "$PYTHON_BIN")"

MISSING=""
for mod in pandas nba_api requests; do
    "$PYTHON_BIN" -c "import $mod" >/dev/null 2>&1 || MISSING="$MISSING $mod"
done
if [ -n "$MISSING" ]; then
    die "$PYTHON_BIN cannot import:$MISSING

  The refresh needs these. Install them for that interpreter, or put the
  one that has them first on your PATH, then run this again:

      $PYTHON_BIN -m pip install pandas nba_api requests

  Checked now rather than at 08:30, because a job that fails then fails
  to nobody."
fi
say "python: $PYTHON_BIN (pandas, nba_api, requests all import)"

mkdir -p "$HOME/Library/LaunchAgents" "$REPO_DIR/logs" || die "could not create directories"

# Errors go next to the refresh log from now on, not into /tmp. The
# whole reason this took three days to spot is that launchd's stderr
# went somewhere nobody looks.
cat > "$PLIST" <<PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by tools/install_refresh_job.sh -- do not hand-edit.
  Re-run that script after moving or renaming the checkout.
-->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$REPO_DIR/tools/scheduled_refresh.sh</string>
    </array>

    <key>WorkingDirectory</key>
    <string>$REPO_DIR</string>

    <!-- scheduled_refresh.sh honours \$PYTHON; without this it would
         fall back to launchd's /usr/bin/python3, which has no pandas.
         PATH carries the same interpreter's directory so anything the
         refresh shells out to finds its neighbours too. -->
    <key>EnvironmentVariables</key>
    <dict>
        <key>PYTHON</key>
        <string>$PYTHON_BIN</string>
        <key>PATH</key>
        <string>$PYTHON_DIR:/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>

    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key><integer>$HOUR</integer>
        <key>Minute</key><integer>$MINUTE</integer>
    </dict>

    <key>RunAtLoad</key>
    <false/>

    <key>StandardOutPath</key>
    <string>$REPO_DIR/logs/launchd.out</string>
    <key>StandardErrorPath</key>
    <string>$REPO_DIR/logs/launchd.err</string>
</dict>
</plist>
PLISTEOF

say "wrote the plist"

launchctl unload "$PLIST" >/dev/null 2>&1   # ignore "not loaded"
launchctl load "$PLIST" 2>/dev/null || die "launchctl load failed"
say "loaded"

echo
STATUS="$(launchctl list | grep "$LABEL" || true)"
if [ -z "$STATUS" ]; then
    die "the job is not in launchctl list -- it did not load"
fi
say "launchctl says: $STATUS"
echo
say "It will run at $(printf '%02d:%02d' "$HOUR" "$MINUTE") daily. The columns above are"
say "PID, last exit code, label -- a '-' for PID just means it is not"
say "running right now, which is correct between runs."
echo
say "To prove it works without waiting for the morning:"
say "    launchctl kickstart -k gui/\$UID/$LABEL"
say "    tail -f $REPO_DIR/logs/refresh.log"
say "A full refresh takes over an hour, so start it when you can leave it."
echo
say "If a morning ever passes with nothing new in logs/refresh.log,"
say "check logs/launchd.err -- that is where the reason lands now."
echo
